### ISSUE TITLE
is there a precompile exe to download?

### ISSUE THREAD

**Issue by pp0236** [Ciremun/kokosu#1]
can't figure out how to include glfw in compiler sorry

**Comment by Ciremun** [comment]
@pp0236 posted a release, precompiled Windows binaries: https://github.com/Ciremun/kokosu/releases/tag/v1.0

How to include glfw?

Dynamic linking, Visual Studio 2022:

download `64-bit Windows binaries` - https://www.glfw.org/download
invoke compiler:
```
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
cl -DIMGUI_USE_STB_SPRINTF -DNDEBUG -O2 *.cpp imgui/*.cpp -Iimgui -Iinclude -Iglfw/include -Fe:kokosu -link glfw/lib-vc2022/glfw3dll.lib user32.lib opengl32.lib -subsystem:windows -entry:mainCRTStartup
```

**Comment by pp0236** [comment]
thanks.
